import {
  Activity,
  BarChart3,
  Bell,
  BellRing,
  Bookmark,
  CalendarDays,
  ClipboardList,
  Compass,
  BriefcaseBusiness,
  Eye,
  FileText,
  Newspaper,
  LayoutDashboard,
  Mail,
  MessageSquare,
  Search,
  Settings,
  ShieldCheck,
  Star,
  Trophy,
  User,
  UserRound,
  Users,
  Video,
  Award,
  Dumbbell,
  TrendingUp,
} from "lucide-react";

export const roleThemes = {
  athlete: {
    eyebrow: "Athlete identity",
    label: "Athlete Passport",
    description: "Build verified identity, proof, clips, and opportunities.",
    accent: "#1BD97B",
    accentMuted: "rgba(27,217,123,0.12)",
    accentGlow: "rgba(27,217,123,0.25)",
    surface: "#06111F",
    surfaceElevated: "#0A1929",
    surfaceBorder: "rgba(27,217,123,0.15)",
    gradient: "linear-gradient(135deg, #06111F 0%, #091E35 100%)",
    badge: "bg-emerald-500/10 text-emerald-400 ring-emerald-500/20",
    home: "/dashboard",
    nav: [
      { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard, group: "Identity" },
      { label: "Discover", href: "/discover", icon: Compass, group: "Identity" },
      { label: "My Profile", href: "/profile", icon: UserRound, group: "Identity" },
      { label: "ProClips", href: "/pro-clips", icon: Video, group: "Proof" },
      { label: "Metrics", href: "/metrics", icon: BarChart3, group: "Proof" },
      { label: "Growth", href: "/growth", icon: TrendingUp, group: "Proof" },
      { label: "Messages", href: "/messages", icon: MessageSquare, group: "Recruitment" },
      { label: "Opportunities", href: "/opportunities", icon: BriefcaseBusiness, group: "Recruitment" },
      { label: "Applications", href: "/applications", icon: ClipboardList, group: "Recruitment" },
      { label: "Bookmarks", href: "/bookmarks", icon: Bookmark, group: "Recruitment" },
      { label: "Activity", href: "/activity", icon: Activity, group: "Progress" },
      { label: "Teams", href: "/teams", icon: Dumbbell, group: "Progress" },
      { label: "Badges", href: "/badges", icon: Star, group: "Progress" },
      { label: "Settings", href: "/settings", icon: Settings, group: "Account" },
    ],
  },
  scout: {
    eyebrow: "Scout command",
    label: "Scout Console",
    description: "Find verified athletes and manage recruitment workflows.",
    accent: "#3B82F6",
    accentMuted: "rgba(59,130,246,0.12)",
    accentGlow: "rgba(59,130,246,0.25)",
    surface: "#050B18",
    surfaceElevated: "#080F20",
    surfaceBorder: "rgba(59,130,246,0.15)",
    gradient: "linear-gradient(135deg, #050B18 0%, #071020 100%)",
    badge: "bg-blue-500/10 text-blue-400 ring-blue-500/20",
    home: "/scout",
    nav: [
      { label: "Dashboard", href: "/scout", icon: LayoutDashboard, group: "Scouting" },
      { label: "Discover", href: "/scout/discover", icon: Compass, group: "Scouting" },
      { label: "Shortlists", href: "/scout/shortlists", icon: Bookmark, group: "Scouting" },
      { label: "ProClips", href: "/scout/proclips", icon: Video, group: "Scouting" },
      { label: "Opportunities", href: "/opportunities", icon: BriefcaseBusiness, group: "Recruitment" },
      { label: "Messages", href: "/messages", icon: MessageSquare, group: "Recruitment" },
      { label: "Notifications", href: "/scout/notifications", icon: BellRing, group: "Recruitment" },
      { label: "Profile", href: "/scout/profile", icon: UserRound, group: "Account" },
      { label: "Settings", href: "/scout/settings", icon: Settings, group: "Account" },
    ],
  },
  academy: {
    eyebrow: "Academy OS",
    label: "Academy Manager",
    description: "Validate athletes, manage rosters, and operate combines.",
    accent: "#F59E0B",
    accentMuted: "rgba(245,158,11,0.12)",
    accentGlow: "rgba(245,158,11,0.25)",
    surface: "#0A0F1A",
    surfaceElevated: "#0D1320",
    surfaceBorder: "rgba(245,158,11,0.15)",
    gradient: "linear-gradient(135deg, #0A0F1A 0%, #0F1525 100%)",
    badge: "bg-amber-500/10 text-amber-400 ring-amber-500/20",
    home: "/academy",
    nav: [
      { label: "Dashboard", href: "/academy", icon: LayoutDashboard, group: "Operations" },
      { label: "Athletes", href: "/academy/athletes", icon: Users, group: "Operations" },
      { label: "Metrics", href: "/academy/metrics", icon: Activity, group: "Verification" },
      { label: "Combines", href: "/academy/combines", icon: CalendarDays, group: "Verification" },
      { label: "Scout Interest", href: "/academy/scouts", icon: Eye, group: "Recruitment" },
      { label: "Search", href: "/academy/search", icon: Compass, group: "Recruitment" },
      { label: "Opportunities", href: "/opportunities", icon: BriefcaseBusiness, group: "Recruitment" },
      { label: "ProClips", href: "/academy/proclips", icon: Video, group: "Recruitment" },
      { label: "Reports", href: "/academy/reports", icon: FileText, group: "Intelligence" },
      { label: "Profile", href: "/academy/profile", icon: UserRound, group: "Account" },
      { label: "Notifications", href: "/academy/notifications", icon: BellRing, group: "Account" },
      { label: "Settings", href: "/academy/settings", icon: Settings, group: "Account" },
    ],
  },
  coach: {
    eyebrow: "Coach lab",
    label: "Coach Lab",
    description: "Coordinate development, film review, and player reports.",
    accent: "#10B981",
    accentMuted: "rgba(16,185,129,0.12)",
    accentGlow: "rgba(16,185,129,0.25)",
    surface: "#061F17",
    surfaceElevated: "#082B20",
    surfaceBorder: "rgba(16,185,129,0.15)",
    gradient: "linear-gradient(135deg, #061F17 0%, #0A2A1E 100%)",
    badge: "bg-emerald-500/10 text-emerald-400 ring-emerald-500/20",
    home: "/coach",
    nav: [
      { label: "Team Board", href: "/coach", icon: LayoutDashboard, group: "Team" },
      { label: "Roster", href: "/coach/roster", icon: Users, group: "Team" },
      { label: "Development", href: "/coach/development", icon: Activity, group: "Performance" },
      { label: "Video Review", href: "/coach/video", icon: Video, group: "Performance" },
      { label: "Reports", href: "/coach/reports", icon: FileText, group: "Performance" },
      { label: "Messages", href: "/messages", icon: MessageSquare, group: "Communication" },
      { label: "Settings", href: "/coach/settings", icon: Settings, group: "Account" },
    ],
  },
  admin: {
    eyebrow: "Trust operations",
    label: "Admin Trust Ops",
    description: "Protect verification, users, platform quality, and trust.",
    accent: "#EF4444",
    accentMuted: "rgba(239,68,68,0.12)",
    accentGlow: "rgba(239,68,68,0.25)",
    surface: "#050709",
    surfaceElevated: "#080B0E",
    surfaceBorder: "rgba(239,68,68,0.15)",
    gradient: "linear-gradient(135deg, #050709 0%, #0A0D12 100%)",
    badge: "bg-red-500/10 text-red-400 ring-red-500/20",
    home: "/admin",
    nav: [
      { label: "Overview", href: "/admin", icon: LayoutDashboard, group: "Platform" },
      { label: "Verification", href: "/admin/verification", icon: ShieldCheck, group: "Trust" },
      { label: "Users", href: "/admin/users", icon: Users, group: "Trust" },
      { label: "Content", href: "/admin/content", icon: Newspaper, group: "Platform" },
      { label: "Reports", href: "/admin/reports", icon: FileText, group: "Intelligence" },
      { label: "Notifications", href: "/notifications", icon: BellRing, group: "Platform" },
      { label: "Settings", href: "/admin/settings", icon: Settings, group: "Account" },
    ],
  },
};
